networks:
  innovator_network:
    driver: bridge

services:
  api:
    build: .
    ports:
      - "8006:5000"
    environment:
      ENVIRONMENT: production
      DB_HOST: 36.253.137.34
      DB_PORT: 5436
      DB_NAME: ${DB_NAME:-social_db}
      DB_USER: ${DB_USER:-innovator_user}
      DB_PASSWORD: ${DB_PASSWORD:-Nep@tronix9335%}
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - innovator_network
