version: '3.8'

services:
  api:
    build: .
    ports:
      - "8006:5000"
    environment:
      ENVIRONMENT: production
      DB_HOST: 36.253.137.34
      DB_PORT: 5436
      DB_NAME: social_db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - .:/app
    restart: unless-stopped

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
